### ISSUE TITLE
when "produces":["application/json;charset=UTF-8"] , it will import fails

### ISSUE THREAD

**Issue by chenxiaolei** [luckymarmot/Paw-SwaggerImporter#1]
like this

```
  "paths": {
    "/pets": {
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "",
        "operationId": "addPet",
        "consumes": [
          "application/json"
        ],
        "produces": [
           "application/json;charset=UTF-8"
        ],
       ...
```

Error: Invalid Swagger file (invalid schema or schema version < 2.0)

remve charset

```
 "produces": [
           "application/json"
        ],
```

will succeed

**Comment by kwent** [comment]
Hi @chenxiaolei,

First thank you a lot for having the time to open this issue.

@mittsh Our current release is using obsolete mimetype schema. Diff is there: https://github.com/swagger-api/swagger-spec/commit/920f46588051395182aa5f62c21091df7eaa021c.

I re `npm install` to fetch latest  `schema.json` [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) Cf. https://github.com/swagger-api/swagger-spec/tree/master/schemas/v2.0 and rebuild a `1.0.1` version.

Here is the new archive: https://github.com/luckymarmot/Paw-SwaggerImporter/releases/tag/v1.0.1

Regards,

**Comment by mittsh** [comment]
@chenxiaolei @kwent I just released this fix (just running a new `npm install` solved as you predicted Quentin...).

You can update in the Paw menu > Extensions > Check Extensions Updates.
