### ISSUE TITLE
root basepath

### ISSUE THREAD

**Issue by tuexss** [luckymarmot/Paw-SwaggerImporter#2]
When I use basepath `"/"` and resourcepath beginning with `/` the importer ends up with `//` for all the resources. Shouldn't this be prevented, or do I need to define the paths differently in the swagger scheme?

**Comment by mittsh** [comment]
@tuexss thanks a lot for pointing this out, it's very true, and I don't think the Swagger Spec says anything specific about whether it should or not have a trailing slash. Though it states:

> The field name MUST begin with a slash.

And in this case you're right, just a `/` should be a valid entry.

**Comment by mittsh** [comment]
To update the extension, go to Paw menu > Extensions > Check for Extensions Updates

**Comment by tuexss** [comment]
thx alot!
