### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lorengreenfield** [luckymarmot/Paw-SwaggerImporter#22]
Hey guys,

I'm having a problem importing swagger 2 files into Paw. I've got the latest importer and I've tried with several swagger files, both directly from URL and files.

To replicate the issue, try with https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/api-with-examples.json

I've attached a screen shot of the error I'm getting. 

![screen shot 2016-06-28 at 11 11 28 am](https://cloud.githubusercontent.com/assets/10803954/16398806/53dee81c-3d21-11e6-8367-e03f358a857d.png)

**Comment by mittsh** [comment]
@lorengreenfield thanks for reporting this! we're working on a big update of our importers (the Swagger one being a major one), it should fix these things and make the quality of Swagger imports a lot better

@JonathanMontane can you make sure this example Swagger file works with our new importer? thx!

**Comment by JonathanMontane** [comment]
@lorengreenfield I just checked the newest (unreleased) Swagger importer with this file, and it passed successfully.

We're currently working on fixing a few things on the importers, which are bundled together now, so I can't give you a clear date for the fix, but we're near the end of the cycle.

**Comment by lorengreenfield** [comment]
Thanks @JonathanMontane, it'll be nice to have swagger importing back. Looking forward to it!

**Comment by JonathanMontane** [comment]
fixed in v2.2.0
