### ISSUE TITLE
definition references not correctly parsed

### ISSUE THREAD

**Issue by klh** [luckymarmot/Paw-SwaggerImporter#24]
_when using swagger references such as:_

```
post:
      tags:
        - Shared
      operationId: CallGeneric_PostInternal
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - text/javascript
        - application/javascript
        - application/json-p
      parameters:
        - name: url
          in: path
          required: true
          type: string
        - name: payload
          in: body
          required: true
          schema:
            $ref: '#/definitions/System.Object'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/System.Object'
      deprecated: false
```

_see $ref: '#/definitions/System.Object'
that links to:_

```
definitions:
  someapi.Endpoints.Apps.Authentication.AuthenticationRequest:
    required: ['']
    type: object
    properties:
      userName:
        type: string
      password:
        type: string
  System.Object:
    required: ['']
    type: object
    properties: {}
```

_is not correctly rendered as object {username:'',password:''}_

**Comment by JonathanMontane** [comment]
I'm not exactly sure what the issue is here.

If you navigate to `#/definitions/System.Object`, you'll obtain the following JSON Schema:

```
{
  required: ['']
  type: 'object',
  properties: {}
}
```

which would be rendered as a JSON Schema Faker Dynamic Value (JSF), with the generated value `{}`.

If you want to have a required username and password, you should edit the JSON Schema to look like

```
definitions:
  ...
  System.Object:
    required: [ 'username', 'password' ]
    type: object
    properties:
      username:
        type: string
      password:
        type: string
```

**Comment by JonathanMontane** [comment]
@klh Do you still have any issues with importing swagger files into Paw ?

**Comment by lumaxis** [comment]
@JonathanMontane I'm not sure if I'm encountering the exact same issue but for me, the imported Swagger definitions look like this:

![screenshot 2016-08-25 02 34 58](https://cloud.githubusercontent.com/assets/406937/17952676/25f6103c-6a6d-11e6-9794-9e9c1cad9e53.png)

What information can I give you to help debug this? A sample definition looks like this:

``` yaml
ErrorResponse:
  type: object
  properties:
    error:
      $ref: "#/definitions/Error"
  required:
    - error
```

**Comment by JonathanMontane** [comment]
Probably found the bug, I'm looking into fixing it right now.

**Comment by JonathanMontane** [comment]
fixed.
