### ISSUE TITLE
Support importing host and schemes attributes as environment variables

### ISSUE THREAD

**Issue by lumaxis** [luckymarmot/Paw-SwaggerImporter#26]
It would be really nice to be able to easily change the protocol and host for an entire imported document.
Maybe import host and protocol as environment variables?

**Comment by JonathanMontane** [comment]
@lumaxis I'll see what I can do. Though this is low priority at the moment.

**Comment by hoegertn** [comment]
I would really like this too. I already implemented it before as #7 but after the change I do not find the correct place to reimplement it.

**Comment by JonathanMontane** [comment]
@hoegertn you can find the real repository here https://github.com/luckymarmot/API-Flow

**Comment by lumaxis** [comment]
This appears to now be part of the importer in version 3. Thanks a bunch @JonathanMontane! 🎉
