### ISSUE TITLE
Option doesn't show up in importable file types list

### ISSUE THREAD

**Issue by govyrl** [luckymarmot/Paw-SwaggerImporter#3]
![screen shot 2015-09-14 at 10 31 40 am](https://cloud.githubusercontent.com/assets/13245168/9856867/20e5be00-5acc-11e5-8064-334c195d2e6a.png)

**Comment by yijiasu** [comment]
Also have this issue

**Comment by mittsh** [comment]
hey guys, it sounds like we have a bug... I'm investigating this, and I'll get back to you asap today!

**Comment by mittsh** [comment]
I just fixed the issue. Now you can update the extension, in the Paw menu > Extensions > Check for Extensions Updates...

@govyrl @yijiasu thanks a lot for reporting this issue!
