### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by drct** [luckymarmot/Paw-SwaggerImporter#30]
After the import of a Swagger file there are only groups in Paw, no actual requests. This is what the console shows:

Event Loaded extension com.luckymarmot.PawExtensions.SwaggerImporter

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

JS Error @serializer failed with error TypeError: Objective-C blocks called as constructors must return an object. {"line":2882,"column":108} [native code]
[native code]
_castParameterToDynamicString
_toDynamicString
_generateUrl
_createPawRequest
_importPawRequest

__iterate
_applyFuncOverGroupTree

__iterate
_applyFuncOverGroupTree
_importPawRequests

promiseReactionJob@[native code]

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

JS Error @resolver caught error TypeError: Objective-C blocks called as constructors must return an object. {"line":2882,"column":108} [native code]
[native code]
_castParameterToDynamicString
_toDynamicString
_generateUrl
_createPawRequest
_importPawRequest

__iterate
_applyFuncOverGroupTree

__iterate
_applyFuncOverGroupTree
_importPawRequests

promiseReactionJob@[native code]

**Comment by JonathanMontane** [comment]
Thanks for the report, I'll look into it!
It seems that one of the url of the Swagger file is incorrectly interpreted by the importer.
Do you have a file that you could share with our support? support@paw.cloud

Thanks!

**Comment by drct** [comment]
No, unfortunately I cannot share the file in question. Sorry.
