### ISSUE TITLE
Import failed - undefined is not an object

### ISSUE THREAD

**Issue by lumaxis** [luckymarmot/Paw-SwaggerImporter#32]
I just tried importing our Swagger file with the new version that ships with 3.1 but ran into the below error. It's probably not easily possible for me to share the entire file, is there anything else I can do to help debugging?

<img width="843" alt="screenshot 2017-04-26 15 41 36" src="https://cloud.githubusercontent.com/assets/406937/25437485/d597bd1c-2a96-11e7-9c34-93c99e3b3f9e.png">

**Comment by JonathanMontane** [comment]
Hi @lumaxis, thanks for the report, I'll look into it.

**Comment by JonathanMontane** [comment]
Hi @lumaxis, could it be possible that one of your paths does not have one of:
```
['get', 'put', 'post', 'delete', 'options', 'head', 'patch']
```
but only some other fields (probably only x-* fields) ?

**Comment by lumaxis** [comment]
@JonathanMontane Yes, we do have one endpoint that only serves our Swagger file and is configured through our middleware, like this:

```yaml
'/swagger.json':
  x-swagger-pipe: swagger_raw
```

**Comment by JonathanMontane** [comment]
That seems to be the issue! We didn't take into account paths that did not have any operations associated with them.

I'll fix it asap

**Comment by lumaxis** [comment]
Awesome 🙂 
This issue is not super time-critical for me personally but I'll still appreciate a quick fix 👍

**Comment by JonathanMontane** [comment]
Can you try and see if this release candidate would work for you?
[com.luckymarmot.PawExtensions.SwaggerImporter.zip](https://github.com/luckymarmot/Paw-SwaggerImporter/files/958618/com.luckymarmot.PawExtensions.SwaggerImporter.zip)

**Comment by lumaxis** [comment]
Yep, works! 🙌

**Comment by JonathanMontane** [comment]
PR https://github.com/luckymarmot/API-Flow/pull/133

**Comment by JonathanMontane** [comment]
fixed by https://github.com/luckymarmot/Paw-SwaggerImporter/releases/tag/v3.0.2
