### ISSUE TITLE
Failed to correctly import swagger yml file due to Content-Type error

### ISSUE THREAD

**Issue by amelnikov-mylivn** [luckymarmot/Paw-SwaggerImporter#33]
Hello.

When I try to import pretty simple swagger yml file I get success message. 
But when I go for each API endpoint I see a warning which means that import was not so successful after all.
Each my path contains blocks like this

```
consumes:
  - "application/json"
produces:
  - "application/json"
```

After import I got this warning
```
Parameter 'Content-Type': '' is not a valid enumeration value of '[application/json]'
```

You can see it [here](https://www.evernote.com/l/AAYnIAeVKvBKIp7XuVGLwsSWcgp4uOzNPnc)

**Comment by JonathanMontane** [comment]
@amelnikov-mylivn this is actually only a warning, the import was successful and it put the `consumes` array of possible values inside the constraints of the `Content-Type` header. If you write `application/json` as the value for this header it will make the warning disappear.

We could improve the behavior by making the Content-Type autofill the value if there is only one value in the `consumes` header, though.
