### ISSUE TITLE
apiKey securityDefinition is not respecting header key

### ISSUE THREAD

**Issue by databus23** [luckymarmot/Paw-SwaggerImporter#34]
Trying to import this swagger definition https://gist.github.com/databus23/848f60539956284e504605d4d9c01bc1

I noticed that the securityDefinition is not correctly mapped:
![image](https://user-images.githubusercontent.com/439223/27696443-e533d106-5cf1-11e7-95b2-f065ea27e6a4.png)

It seems the header name is ignored. It should be `X-Auth-Token` not `Authorization`.

This is unfortunate because I need to change it for every request after importing it.

**Comment by databus23** [comment]
Seems like its hardcoded [here](https://github.com/luckymarmot/Paw-SwaggerImporter/blob/b185b386e2ccf8861109dd8fad567bcacd1e0102/SwaggerImporter.js#L16531). I have no idea how to fix it though

**Comment by alupher** [comment]
+1. @JonathanMontane, any progress on this bug? Just downloaded Paw for a trial today and ran into this when importing our swagger json.

**Comment by mittsh** [comment]
@databus23 @alupher Apologies for the super long delay on this issue. I have just released a bugfix update to the Swagger importer ([v3.0.3](https://github.com/luckymarmot/Paw-SwaggerImporter/releases/tag/v3.0.3)).

You should now be able to update by going to the Paw menu > Extensions > Check for Extensions Updates.

I hope this helps!
