### ISSUE TITLE
Import fails with swagger.json

### ISSUE THREAD

**Issue by hoegertn** [luckymarmot/Paw-SwaggerImporter#6]
The swagger file from: https://ergebnis.radball-bw.de/swagger.json fails with schema errors. Is there any kind of debug log available to find the reason? the file works perfectly in swagger-ui

**Comment by hoegertn** [comment]
any idea?

**Comment by hishnash** [comment]
@hoegertn 
I get:

```
20/11/2015 11:19:35.480 Paw[234]: LMImporterExtension+LMImporter: Import: JavaScript Exception: Error: Invalid Swagger file (invalid schema or schema version < 2.0) ({
    column = 24;
    line = 181;
})
```

I will have a look to see were this is coming from.

**Comment by hoegertn** [comment]
Yes, but the file is a valid swagger json. Swagger UI is able to parse it correctly

**Comment by hishnash** [comment]
http://editor.swagger.io/#/

if you load it here i get an error:

```
✖ Swagger Error
Missing required property: info
Jump to line 0
Details
 Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY"
message:  "Missing required property: info"
 path: Array [0]
level: 900
type:  "Swagger Error"
description:  "Missing required property: info"
lineNumber: 0
```

**Comment by hoegertn** [comment]
Ok then I will have a look at the file and search the bug in the swagger generator

Thanks for having a look at it

**Comment by hishnash** [comment]
as a work around for know you can load it `http://editor.swagger.io/#/` and then click `FILE->download json` PAW can open this.

**Comment by hoegertn** [comment]
Ok I fixed some fields and now it works. I will create further issues for some improvements, but I will have a look at the source and try to create PullRequests. This issues was causes by the generator creating invalid spec file

**Comment by mittsh** [comment]
@hoegertn great! we will try to improve the error reporting in the Paw importer, it would be nicer to show you precisely why it's failing.
