### ISSUE TITLE
Import host information as environment

### ISSUE THREAD

**Issue by hoegertn** [luckymarmot/Paw-SwaggerImporter#7]
Would it be possible to create an environment and set the host from the swagger.json as variable into the requests? This would allow to import swagger files and run against different servers (dev,stage,prod) without changing every request

**Comment by hishnash** [comment]
@hoegertn i have created a branch that has this functionality. 
https://github.com/luckymarmot/Paw-SwaggerImporter/tree/setHostAsEnv
It would be nice to have a ui for an importer, but for know i hope this helps.

To install you will need:
git, npm (v2.11.3) aka node (v0.12.7)

then checkout setHostAsEnv branch.

```
npm install
npm install -g cake
npm install -g coffee-script
npm install mkdirp ncp
cake build
cake install
```

This will install into your Paw.app

Let me know if this helps.

**Comment by hoegertn** [comment]
Great. I will check this today.

**Comment by hishnash** [comment]
[com.luckymarmot.PawExtensions.SwaggerImporter.zip](https://files.zenhub.io/56532b8a7ec9ca497289e914)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

I have added the compiled plugin: you need to unzip it and add it to: you extensions folder. (to find this open preferences from Paw and click extensions tab)
![image](https://cloud.githubusercontent.com/assets/838127/11340143/eb6a3856-91fc-11e5-934f-a09b29e8a0c7.png)

click "open extensions Directory": replace the existing swagger importer with the folder within this zip file.

**Comment by hoegertn** [comment]
Hi,

import works like charm. Some points to improve it even further:
- There is a typo in the name of the domain "hostEvnDomain"
- Maybe it is possible to use the "title" of the group as env domain name
- Please add the scheme to the variable "<scheme>://<host>" to allow to change this globally to.

My main use case is to test against http://localhost and https production
