### ISSUE TITLE
URL Import

### ISSUE THREAD

**Issue by nVitius** [luckymarmot/Paw-SwaggerImporter#9]
It would be nice to have the ability to import a swagger definition given a URL.

**Comment by mittsh** [comment]
That's a good point @nVitius, it would require some changes on our side, but it surely is a very useful thing. We have a big UI/UX oriented update scheduled for the coming months so we will bundle this in.

**Comment by letsbyteit** [comment]
Also looking for URL orientated imports, any news on this, @mittsh?

**Comment by mittsh** [comment]
Yes absolutely! We're working on it. They should come in about 2 weeks.

**Comment by letsbyteit** [comment]
That sounds great, thanks!

**Comment by JonathanMontane** [comment]
@letsbyteit, @nVitius you can now import swagger files from urls.
